In [15]:
import numpy as np

# build examples
dataWidth = 6
minSlope = -3
maxSlope = 3

# build varying slopes
def generateSlopes():
    dataset = None
    i=0
    slope = np.empty(maxSlope-minSlope+1)
    for currentSlope in range (minSlope, maxSlope+1):
        slope[i] = currentSlope
        lastValue = 0
        if (currentSlope == 0):
            newdata = np.zeros(dataWidth)
        else:
            newdata = np.arange(0, dataWidth*currentSlope, currentSlope)
        if (dataset is None):
            dataset = newdata
        else:
            dataset = np.vstack((dataset, newdata))
        i+=1
    return dataset    

def knockOutHoles(dataset):
    for row in dataset:
        row[3] = 0
    return dataset

dataset = generateSlopes()
dataset = knockOutHoles(dataset)

print(dataset)

[[  0.  -3.  -6.  -9. -12. -15.]
 [  0.  -2.  -4.  -6.  -8. -10.]
 [  0.  -1.  -2.  -3.  -4.  -5.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   1.   2.   3.   4.   5.]
 [  0.   2.   4.   6.   8.  10.]
 [  0.   3.   6.   9.  12.  15.]]
